@startuml
left to right direction
Actor "utente" as User
package "Rubrica contatti: Dashboard"{


'Usecases principali:
usecase "Aggiunta Contatto" as UC1
usecase "Modifica Contatto" as UC2
usecase "Rimozione Contatto" as UC3
usecase "Ricerca Contatto" as UC4
usecase "Carica File" as CF
usecase "Salva File" as SF
usecase "Conferma ricerca" as UC4.1
'casi di include:
usecase "Conferma" as Conf
usecase "Indietro" as Ind
}
package "System" {
usecase "Aggiornamento rubrica" as UC5
}
package "Error Messages"{
'casi di extends
package "Format Error Messages" as FEM {
usecase "MailFormatError" as MFE
usecase "NumberFormatError" as NFE
}
usecase "FileError" as FE
usecase "SearchError" as SE
usecase "NameSurnameError" as NSE
}
CF <.. FE : <<extends>>
SF <.. FE : <<extends>>
User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> CF
User --> SF
User --> Ind


UC1 ..> Conf : <<includes>>
UC2 ..> Conf : <<includes>>
UC3 ..> Conf : <<includes>>
UC1 <.. FEM : <<extends>>
UC4.1 <.. SE : <<extends
UC2 <.. FEM : <<extends>>
UC3 <.. FEM : <<extends>>
Conf <.. NSE : <<extends>>
UC4 ..> UC4.1 : <<includes>>
Conf ..> UC5 : <<includes>>
@enduml
